### ISSUE TITLE
Add link to github repository in the docs

### ISSUE THREAD

**Issue by ShaiAvr** [qurit/PyTomography#107]
I find it slightly annoying that there is no direct link in the documentation to the GitHub repository. Since you are using the `pydata` theme, it is extremely easy to add links to GitHub and any other external resources which are easily available on the top of the site. Look at the docs of `pydata` itself for example:

![Screenshot 2023-11-05 102950](https://github.com/qurit/PyTomography/assets/35605235/f35b7512-6990-4043-b6a4-0914d24cdaf8)

Adding such a link to GitHub is as simple as adding:
```python
html_theme_options = {
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/qurit/PyTomography",
            "icon": "fa-brands fa-github",
            "type": "fontawesome",
        },
    ],
}
```
to `conf.py`. If there are no objections or issues, I can make a PR to implement this change.

**Comment by lukepolson** [comment]
Sorry for super late reply, this will be fixed in the next update
