### ISSUE TITLE
no attribute RadialPosition in some dicom vendor's files

### ISSUE THREAD

**Issue by ludicludo** [qurit/PyTomography#112]
**GEHC** Tandem_Discovery_670  NM dicom files has no attribute RadialPosition to be discovered by pydicom.
here's a traceback output:
```
site-packages\pytomography\io\SPECT\dicom.py", line 60, in parse_projection_dataset

    radial_positions_detector = ds.DetectorInformationSequence[detector-1].RadialPosition ...

site-packages\pydicom\dataset.py", line 908, in __getattr__
    return object.__getattribute__(self, name)

AttributeError: 'Dataset' object has no attribute 'RadialPosition'
```
Maybe, one could add the attribute in case it is missing.

**Comment by ludicludo** [comment]
Hi Luke,
This bug is still present in the v 1.3.2. The modification in the pull request were not effective?
Best regards

**Comment by lukepolson** [comment]
Its been merged with the development branch; the next time I release a main version it will be merged and added
