### ISSUE TITLE
Installation of PyTorch should be done by installation of PyTomography

### ISSUE THREAD

**Issue by carluri** [qurit/PyTomography#15]
The documentation says to create an environment for PyTomography, followed by the installation of PyTorch, and then followed by the installation of PyTomography.

PyTomography clearly requires PyTorch. This should be set as a requirement either in a `requirements.txt` file or in the `setup.cfg` one.

When `pip install pytomography` is executed PyTorch will be installed if not already on the system.

**Comment by lukepolson** [comment]
The issue with this is that PyTorch installation requires careful consideration of the graphics card of the users system, and can't be automatically installed like other packages. See

https://pytorch.org/
