### ISSUE TITLE
SPECT dicom output

### ISSUE THREAD

**Issue by sarakurkowska** [qurit/PyTomography#158]
Improve the dicom output of modality NM:
 - Series Description - change
 - 'RotationInformationSequence' tag - add

**Comment by sjswerdloff** [comment]
> Improve the dicom output of modality NM:
> 
> * Series Description - change
> * 'RotationInformationSequence' tag - add

Series Description is being copied from the projection data:
https://github.com/qurit/PyTomography/blob/9bd1a56a3f10108f11de4326653cc49e21ff4e4e/src/pytomography/io/SPECT/dicom.py#L721

What change is desired? (I'm not a current contributor yet, but I know DICOM and I'm familiar with SPECT)

The same line of code as above is where the RotationInformationSequence needs to be added to the list of elements to copy.

**Comment by sarakurkowska** [comment]
Hey, no worries. I'm familiar with DICOM and SPECT, and I'll work on that. There are a couple of tags I wanted to improve, but I was traveling, so I started to put the notes in here to make sure they don't get lost

**Comment by sjswerdloff** [comment]
Digging a little deeper, the Number of Rotations for a RECON TOMO is supposed to be 1, so how does one reconcile the need to have a single item in the RotationInformationSequence if the TOMO itself had multiple rotations (and multiple items in the RotationInformationSequence)?  I put in a PR, but hadn't dug through the consequences.
https://dicom.innolitics.com/ciods/nuclear-medicine-image/nm-multi-frame/00540051

> C.8.4.8.1.5 Number of Rotations and Rotation Vector
> Number of Rotations (0054,0051) is the number of separate rotations. See [Section C.8.4.12](https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.4.12.html) for definition of a rotation. When Image Type (0008,0008), Value 3, is RECON TOMO, GATED TOMO or RECON GATED TOMO, then the Number of Rotations (0054,0051) shall be 1.

**Comment by lukepolson** [comment]
Closing because this was validated in MIM and reconstructed images can be opened
