### ISSUE TITLE
Table / Code to Obtain PSFMeta From DICOM Files Given Scanner Model

### ISSUE THREAD

**Issue by lukepolson** [qurit/PyTomography#42]
Main goal: obtain `collimator_slope` and `collimator_intercept` from DICOM file (parameters for `PSFMeta`). For this...

- Get scanner name from SPECT DICOM file
- Create data table to go from scanner name to get appropriate parameters required to obtain `collimator_slope` and `collimator_intercept`. These will be things like crystal length, hole diameter, etc.
- Write function (in `pytomography.io.dicom`) that takes in SPECT dicom file, and obtains `collimator_slope` and `collimator_intercept`
- Reach out to MIM team for validation with their private parameter files.

**Comment by ObedDzik** [comment]
Added a table for SymbiaTSeries and attenuation values for lead to write a baseline code.

**Comment by lukepolson** [comment]
Close with #65
